POST http://localhost:5000/userTask/createUserTask
Content-Type: application/json

{
    "myTaskTitle":"aaaaaaa",
    "myTaskDescription":"bbbbbbbbbbbb"
}

###
POST http://tranquil-escarpment-92025.herokuapp.com/userTask/createUserTask
Content-Type: application/json

{
    "myTaskTitle":"deploy to heroku",
    "myTaskDescription":"important to connect client app with server"
}

###

GET http://localhost:5000/userTask/getUserTask

###
